name: EOSIO Vulnerability Scanner

on:
  push:
    branches:
      - main # Replace with the branch you intend to run this action against.

jobs:
  eosio_vulnerability_scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Scan EOSIO files
      uses: Sentnl/eosio-vulnerability-scanner@main
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        engine: 'text-davinci-003'  # Replace with the desired engine identifier

    - name: Upload vulnerability report
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-report
        path: ./**/*_vulnerabilities.txt
